# Generated by Django 3.2.8 on 2023-08-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='other_info',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_info',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
